name: Build and Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy: 
    name: Build and Deploy Spring boot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with: 
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

#Running Multiple files
      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
            
#Pushing it to Docker  
          
